version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
  users-db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

