version: '3'
# todo update
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=users-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - MONGO_USER=root
      - MONGO_PASSWORD=123
    depends_on:
      - users-db
      - messages-db
  users-db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    logging:
      driver: none
    volumes:
      - postgres-data:/var/lib/postgresql/data
  messages-db:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
    logging:
      driver: none

volumes:
  postgres-data:
  mongo-data:

